#!/usr/bin/with-contenv bash

# If the config-source directory exists, copy over to /config
if [ -d /config-source ]; then
    echo "Copying config from source..."
    rsync -rt /config-source/ /config/
    chown -R abc:abc /config
fi